# Generated by Django 2.0.7 on 2020-08-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaiwanFruits', '0002_fruits_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruits',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
