# Generated by Django 2.0.7 on 2020-08-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaiwanFruits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruits',
            name='Name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fruits',
            name='certificate',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='fruits',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fruits',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='fruits',
            name='price_each',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='price_per_pound',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
