# Generated by Django 2.0.7 on 2020-08-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaiwanFruits', '0002_auto_20200828_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruits',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='image',
        ),
    ]
