# Generated by Django 2.1.5 on 2020-08-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaiwanFruits', '0003_auto_20200828_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruits',
            name='certificate',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='fruits',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fruits',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fruits',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
