# Generated by Django 2.1.5 on 2020-08-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaiwanFruits', '0004_auto_20200828_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruits',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='price_each',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='price_per_pound',
        ),
        migrations.AddField(
            model_name='fruits',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruits',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruits',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fruits',
            name='title',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
